#!/bin/bash

DB_PASS="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13)"

BOOKSTACK_DIR="/var/www/bookstack"

DOMAIN="wiki2.sdshmlb.com"

MYSQL="10.2.0.2"

LOGPATH=$(realpath "bookstack_install_$(date +%s).log")

# Get the current user running the script
SCRIPT_USER="${SUDO_USER:-$USER}"

# Get the current machine IP address
CURRENT_IP=$(ip addr | grep 'state UP' -A4 | grep 'inet ' | awk '{print $2}' | cut -f1  -d'/')

LOGPATH=$(realpath "bookstack_install_$(date +%s).log")

# Get the current user running the script
SCRIPT_USER="${SUDO_USER:-$USER}"


run_package_installs() {
  apt update
  apt install -y git unzip apache2 php8.1 curl php8.1-curl php8.1-mbstring php8.1-ldap \
  php8.1-xml php8.1-zip php8.1-gd php8.1-mysql libapache2-mod-php8.1
}

# Download BookStack
run_bookstack_download() {
  cd /var/www || exit
  git clone https://github.com/BookStackApp/BookStack.git --branch release --single-branch bookstack
}



run_package_installs
run_bookstack_download
